### ISSUE TITLE
Should be in supercollider distribution

### ISSUE THREAD

**Issue by sonoro1234** [dyfer/PitchShiftPA#1]
As there is no equivalent UGen for such a classic

**Comment by sonoro1234** [comment]
To implement autotune should be necessary to get the nearest frequency to detected frequency from a set of given frequencies.
How this could be done in SC?

**Comment by dyfer** [comment]
Thanks for your interest @sonoro1234!

I would argue, that while this implementation works good in certain cases, it's tricky to use reliably - it depends on accurate pitch tracking and only works for monophonic signals with little to no background sounds (especially crosstalk from other pitched sources). I think that in order to be in the regular SC distribution, it would need to perform better. But if there are more SC devs that would like to see this included, I'd be happy to revisit the idea. Feel free to re-open this if more devs would like to see this included in SC.

Regarding the auto-tune, I've put together an example and added it to the help file: https://github.com/dyfer/PitchShiftPA/commit/e8e2520897d1ba302a85a0bfe24cf9a064d819b1

Enjoy!
